import type { Express } from "express";
import type { Server } from "http";
import { storage } from "./storage";

const ADMIN_PASSWORD = "salty2026";

const SEED_STOPS = [
  // HISTORICAL
  { name: "Brimstone Hill Fortress", category: "historical", description: "Dubbed the Gibraltar of the Caribbean, this UNESCO World Heritage Site is one of the best-preserved fortress complexes in the Americas. Built over a century by enslaved Africans under British military direction, it crowns a 972-foot volcanic hill with sweeping views across the Caribbean Sea to neighboring islands. Took over 100 years to complete and was considered impregnable by 1780.", tip: "Arrive early morning before the cruise ship crowds. The views from the citadel at sunrise are unreal.", duration: "2–3 hours", lat: 17.3469, lng: -62.8364, area: "Sandy Point", featured: true },
  { name: "Romney Manor & Caribelle Batik", category: "historical", description: "A 17th-century estate once linked to the family of Thomas Jefferson, now home to Caribelle Batik — a working studio where artisans handcraft vivid fabrics using centuries-old wax-resist techniques. Eight acres of botanical gardens surround the Great House, anchored by a magnificent 400-year-old saman tree said to be the largest living organism on the island.", tip: "Watch the batik artists at work for free. The studios are open and the fabrics are the real deal.", duration: "1–1.5 hours", lat: 17.3257, lng: -62.8009, area: "Old Road", featured: false },
  { name: "Wingfield Estate Sugar Plantation Ruins", category: "historical", description: "The oldest sugar estate and rum distillery ruins in the Eastern Caribbean, dating to the early 1600s. Among the crumbling stone mills, ancient Kalinago petroglyphs carved over 2,000 years ago can still be found on boulders at the edge of the rainforest. An active archaeological excavation means the site keeps revealing more.", tip: "⚠️ We always recommend hiring a local guide for hikes in St Kitts. Ask about the petroglyphs — easy to miss on your own.", duration: "45–90 minutes", lat: 17.3249, lng: -62.7995, area: "Old Road", featured: false },
  { name: "Independence Square", category: "historical", description: "The historic heart of Basseterre. This leafy colonial square served as the administrative, commercial, and social center of the island from the 1750s — and for a period, a slave market. Where the fountain stands today, enslaved people were once sold. Renamed on September 19, 1983, the day St Kitts gained independence.", tip: "Best photographed in early morning light. Liveliest on weekend mornings when locals gather.", duration: "20–30 minutes", lat: 17.2948, lng: -62.7241, area: "Basseterre", featured: false },
  { name: "The Circus & Berkeley Memorial", category: "historical", description: "The commercial heart of Basseterre, modeled on London's Piccadilly Circus. The Victorian-era Berkeley Memorial — a green cast-iron clock tower and drinking fountain built in 1883 — anchors the roundabout. Locals call it Little Ben. Its four faces each point down one of the city's main streets.", tip: "The upper floor of the bakery on the Circus gives you a perfect overhead angle on the memorial.", duration: "15–20 minutes", lat: 17.2950, lng: -62.7236, area: "Basseterre", featured: false },
  { name: "St George's Anglican Church", category: "historical", description: "The largest church in Basseterre, standing at the head of Church Street. Rebuilt multiple times after fires and hurricanes — most recently after Hurricane Hugo in 1989. The graveyard contains headstones dating back to the 1600s. Entry is free and the grounds are open during daylight hours.", tip: "Look for the oldest grave markers in the far corners of the cemetery.", duration: "20–30 minutes", lat: 17.2962, lng: -62.7191, area: "Basseterre", featured: false },
  { name: "Immaculate Conception Co-Cathedral", category: "historical", description: "A striking Roman Catholic cathedral with twin towers dominating the eastern side of Independence Square. The current structure was completed in 1928 and elevated to co-cathedral status in 1981. The grey stone exterior and ornate interior reflect the island's French and British colonial heritage. Cool, quiet, and beautiful inside.", tip: "Particularly striking at dusk when the setting sun hits the stonework.", duration: "15–20 minutes", lat: 17.2964, lng: -62.7215, area: "Basseterre", featured: false },
  { name: "Old Road Bay & Town", category: "historical", description: "This small fishing village marks the exact spot where Sir Thomas Warner landed in 1623 to establish the first permanent British settlement in the Caribbean. The unhurried village retains its weathered character with colorful fishing boats drawn up on the shore. One of the most historically significant sites in the entire Caribbean — and most visitors drive right past it.", tip: "Stop at the historical marker near the bay before heading to Wingfield Estate nearby.", duration: "30–45 minutes", lat: 17.3222, lng: -62.8034, area: "Old Road", featured: false },
  { name: "Fairview Great House & Botanical Gardens", category: "historical", description: "The only surviving French colonial plantation great house on St Kitts, built circa 1701 to house French military officers. Fully restored and furnished with period antiques, surrounded by meticulously maintained tropical botanical gardens. A rare piece of French colonial architecture on an otherwise British-dominated island.", tip: "Fairview occasionally hosts candlelit dinners on the veranda — worth checking the schedule.", duration: "1–1.5 hours", lat: 17.2978, lng: -62.7702, area: "Boyd's", featured: false },
  { name: "National Museum of St Kitts", category: "historical", description: "Housed in the 1894 Old Treasury Building near Port Zante, this museum covers the full arc of Kittitian history — from pre-Columbian Kalinago settlement through slavery, emancipation, the sugar economy, and independence. Compact enough to tour in an hour. Entry around USD $5. The best single place to understand the island before you explore it.", tip: "Make this your first stop on any Basseterre walking tour. The context makes every other site hit different.", duration: "45–75 minutes", lat: 17.2955, lng: -62.7226, area: "Basseterre", featured: false },
  { name: "Port Zante & Basseterre Waterfront", category: "historical", description: "The cruise pier sits at the heart of Basseterre with walking access to the Circus, Independence Square, and the National Museum. The waterfront promenade offers views across the harbor to Nevis. A solid starting point for a walking tour of the capital even if you are not arriving by ship.", tip: "Grab a coconut water from a street vendor before heading into town.", duration: "30–45 minutes", lat: 17.2928, lng: -62.7228, area: "Basseterre", featured: false },
  { name: "Bloody Point", category: "historical", description: "In 1626, English and French colonists united to massacre an estimated 2,000 Kalinago people at this site, ending indigenous resistance to European colonization of St Kitts. The river that once ran red with blood gave this place its name. One of the most consequential and disturbing sites in Caribbean colonial history. It deserves to be known.", tip: "No formal visitor infrastructure — it is a roadside site. Pull over, read the history, let it land.", duration: "15–20 minutes", lat: 17.3033, lng: -62.7885, area: "Old Road", featured: false },
  { name: "Sir Thomas Warner Gravestone", category: "historical", description: "In the churchyard of St Thomas Middle Island Church lies the grave of Sir Thomas Warner, the first English governor of the West Indies and founder of the British settlement on St Kitts in 1623. Beside him is the grave of Samuel Jefferson — great-grandfather of US President Thomas Jefferson. This modest churchyard holds the remains of people who shaped the entire hemisphere.", tip: "The grave markers are simple and easy to miss. Take a moment with it.", duration: "15–20 minutes", lat: 17.3275, lng: -62.8138, area: "Middle Island", featured: false },
  { name: "Kalinago Rock Petroglyphs", category: "historical", description: "Ancient carvings made by the Kalinago people more than 2,000 years ago, etched into boulders near Wingfield Estate at the edge of the rainforest. Believed to express the religious beliefs and ceremonial practices of the indigenous people who inhabited these islands long before European contact. A quiet and powerful reminder of who was here first.", tip: "⚠️ We always recommend hiring a local guide for hikes in St Kitts. Easy to miss without someone who knows where to look.", duration: "30–45 minutes", lat: 17.3245, lng: -62.7990, area: "Old Road", featured: false },
  { name: "Old Road Rum Distillery", category: "historical", description: "The oldest surviving rum distillery on St Kitts, rooted in the island's centuries-long sugar and rum heritage. Visitors can tour the distillery, learn about the production process, and make a personalized bottle. Rum is not just a drink here — it is the liquid history of the island's sugar economy, colonial labor, and Kittitian identity.", tip: "The hands-on bottle-making experience is worth doing. Book ahead during cruise ship season.", duration: "1–1.5 hours", lat: 17.3247, lng: -62.7998, area: "Old Road", featured: false },
  { name: "The War Memorial & Cenotaph", category: "historical", description: "Located in Fortlands at the end of Bay Road, this cenotaph was unveiled by Princess Margaret in 1955 with two brass plaques commemorating Kittitians who served and died in both World Wars. A modest but moving monument to the men and women of this small island who went to fight in conflicts on the other side of the world.", tip: "Most visitors drive past without stopping. It deserves a moment.", duration: "10–15 minutes", lat: 17.2950, lng: -62.7242, area: "Basseterre", featured: false },
  { name: "St Kitts Scenic Railway", category: "historical", description: "The last surviving railway in the Eastern Caribbean, originally built between 1912 and 1926 to haul sugarcane from the fields to the central sugar factory in Basseterre. Today it operates as a heritage tour on a narrow-gauge track that circles roughly two-thirds of the island on a scenic double-decker train through villages, coastline, and former plantation land.", tip: "Book in advance — tour groups fill this up fast. The upper deck gives the best views.", duration: "3–3.5 hours", lat: 17.3131, lng: -62.7113, area: "Basseterre", featured: false },
  { name: "Old Treasury Building", category: "historical", description: "Constructed in 1894 from hand-cut blocks of local volcanic andesite stone, the Old Treasury Building is one of the most architecturally significant structures in Basseterre. Its iconic archway once served as the entry portal for passengers arriving by ship, and the dome on top functioned as a lighthouse. Now houses the National Museum and the St Christopher National Trust.", tip: "The building itself is the exhibit. Walk through the archway and look up — the stonework is extraordinary.", duration: "15–20 minutes", lat: 17.2956, lng: -62.7227, area: "Basseterre", featured: false },
  { name: "Shadwell Great House", category: "historical", description: "One of St Kitts' lesser-known but historically significant plantation great houses, sitting on the eastern side of the island away from the main tourist circuit. The estate dates to the colonial sugar era and the ruins and surrounding landscape offer a raw, unpolished look at plantation history without the crowds found at more well-known sites.", tip: "Not on the standard tour circuit — which is exactly why it is worth finding.", duration: "30–45 minutes", lat: 17.3066, lng: -62.7357, area: "Eastside", featured: false },
  // THE BUSH (nature)
  { name: "Mount Liamuiga Volcano Trail", category: "nature", description: "At 3,792 feet, Mount Liamuiga is the highest point in St Kitts — a dormant stratovolcano with its summit perpetually wrapped in cloud. The trail climbs through agricultural land, then dense primary rainforest draped in giant ferns and elephant ears, to the rim of a massive volcanic crater locals call the Giants Salad Bowl. On a clear day you can see six neighboring islands from the top.", tip: "⚠️ We always recommend hiring a local guide for hikes in St Kitts. Round trip to the crater rim takes 4–6 hours. Hire a guide from Saint Pauls village — the final section is steep and unforgiving.", duration: "4–6 hours", lat: 17.3696, lng: -62.8034, area: "Sandy Point", featured: true },
  { name: "Wingfield Rainforest & Estate Trails", category: "nature", description: "A network of trails through the verdant rainforest on the lower slopes of Mount Liamuiga, winding past towering mahogany trees, giant ferns, wild orchids, and the ruins of the oldest sugar estate in the Eastern Caribbean. The trails connect to the estate archaeological site and the Kalinago petroglyphs. Multiple difficulty levels — shorter loops work for most fitness levels.", tip: "⚠️ We always recommend hiring a local guide for hikes in St Kitts. Start at Wingfield Estate and combine with Romney Manor for a full morning in this area.", duration: "1–3 hours", lat: 17.3249, lng: -62.7995, area: "Old Road", featured: false },
  { name: "Dos D'Anse Pond Trail", category: "nature", description: "A less-traveled trail leading to one of the island's quieter interior ponds, passing through dense tropical vegetation with good birdwatching along the way. The kind of spot most tourists never find — which is exactly the point.", tip: "⚠️ We always recommend hiring a local guide for hikes in St Kitts. This trail rewards the curious. Not well-marked — a local guide is strongly recommended.", duration: "1.5–2.5 hours", lat: 17.3366, lng: -62.795, area: "Old Road", featured: false },
  { name: "Bloody Point Rainforest Trail", category: "nature", description: "A trail through lush rainforest that passes through the area surrounding Bloody Point — the 1626 massacre site where English and French colonists killed an estimated 2,000 Kalinago people. The trail combines raw natural beauty with some of the heaviest history on the island. The forest here is dense and the birdlife is exceptional.", tip: "⚠️ We always recommend hiring a local guide for hikes in St Kitts. The history of this area adds weight to every step. Know what happened here before you walk it.", duration: "1.5–2.5 hours", lat: 17.3033, lng: -62.7885, area: "Old Road", featured: false },
  { name: "Brimstone Hill Fortress Trails", category: "nature", description: "The grounds of the UNESCO World Heritage fortress include walking trails through the outer defenses, bastions, and hillside scrub with sweeping 360-degree views across the Caribbean. The elevation and sea breeze make it one of the most pleasant walking experiences on the island, even in the heat of the day.", tip: "⚠️ We always recommend hiring a local guide for hikes in St Kitts. Combine the fortress trails with the full historical tour of the citadel. Good shoes essential — the volcanic stone paths are uneven.", duration: "1–2 hours", lat: 17.3469, lng: -62.8364, area: "Sandy Point", featured: false },
  { name: "Central Forest Reserve Trails", category: "nature", description: "Trails through the heart of St Kitts' protected Central Forest Reserve, covering the mid-elevation rainforest on the slopes of Mount Liamuiga. This is where the island's biodiversity is most concentrated — tree ferns, bromeliads, Antiguan racer habitat, and the calls of the Caribbean Elaenia and Antillean crested hummingbird. Largely undisturbed and genuinely wild.", tip: "⚠️ We always recommend hiring a local guide for hikes in St Kitts. One of the least-visited trail areas on the island. A local guide is essential for navigation.", duration: "2–4 hours", lat: 17.3331, lng: -62.7894, area: "Central St Kitts", featured: false },
  { name: "Verchilds Mountain & Phillips Trails", category: "nature", description: "Trails on the eastern slopes of the central mountain range around Verchilds and the Phillips area — a quieter, less-trafficked part of the island's highland terrain. The trails pass through secondary forest and offer views down to the Atlantic coast villages below. Good for birdwatching and for getting off the beaten path.", tip: "⚠️ We always recommend hiring a local guide for hikes in St Kitts. This area is genuinely off the tourist map. Come with a guide who knows the terrain.", duration: "2–3 hours", lat: 17.3554, lng: -62.7849, area: "Eastside", featured: false },
  { name: "Shitten Bay & Southeast Peninsula Trails", category: "nature", description: "The dry scrub forest and volcanic ridgelines of the Southeast Peninsula hold some of the island's most dramatic coastal hiking — hidden coves, salt ponds, vervet monkey territory, and views of both the Caribbean and Atlantic simultaneously. Shitten Bay is a remote, untouched stretch of coastline that few visitors ever reach. The name is not a deterrent — the place is stunning.", tip: "⚠️ We always recommend hiring a local guide for hikes in St Kitts. ⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts. Trail conditions vary — come prepared with water and sun protection.", duration: "1.5–3 hours", lat: 17.22528, lng: -62.66228, area: "Southeast Peninsula", featured: false },
  // LIME & DINE
  { name: "Mr. X's Shiggidy Shack", category: "food_nightlife", description: "The most beloved beach bar on The Strip at South Frigate Bay. Cold Caribs, killer rum punches, and good vibes that make you miss your flight home. Wednesday nights are legendary for trivia, Thursday nights bring the famous buffet, and Saturdays go late with karaoke. This is the move.", tip: "Wednesday Trivia Night is a must — the host is hilarious, the crowd is mixed local and tourist, and teams get seriously competitive.", duration: "2–4 hours", lat: 17.28057, lng: -62.68701, area: "The Strip, Frigate Bay", featured: true },
  { name: "Sprat Net Bar & Grill", category: "food_nightlife", description: "One of the most authentic local dining experiences on St Kitts. A rustic open-air pavilion at Old Road Bay where you pick your own fish from the display and watch it grilled to order, served with corn, potatoes, and Johnny cakes. On Wednesday and Saturday nights, live Caribbean bands fill the air under the stars.", tip: "Wednesday nights feature the best live music on this side of the island — the scene is lively, local, and completely unpretentious.", duration: "1.5–3 hours", lat: 17.32, lng: -62.8008, area: "Old Road Town", featured: false },
  { name: "El Fredo's", category: "food_nightlife", description: "A proper local spot in Basseterre that doesn't advertise to tourists — and that's exactly why you should go. Some of the best BBQ ribs on the island alongside rice and peas, stewed chicken, and whatever the kitchen feels like cooking that day. The kind of place where the food is made by someone's grandmother.", tip: "Cash only. Portions are generous and things run out. Go before 1pm.", duration: "45–75 minutes", lat: 17.29800, lng: -62.72600, area: "Basseterre", featured: false },
  { name: "17\u00b062\u00b0 Gibraltar Gastrolounge", category: "food_nightlife", description: "Perched on top of Brimstone Hill Fortress — a UNESCO World Heritage Site — this is one of the most dramatically located restaurants in the entire Caribbean. Chef O'Keeffe Marshall's menu covers New American, Caribbean, and Thai fusion territory built around locally sourced ingredients. The views are ridiculous. The cocktails are serious.", tip: "Open daily 11am–4pm. Book ahead — it fills up fast on cruise ship days.", duration: "1.5–2.5 hours", lat: 17.3469, lng: -62.8364, area: "Brimstone Hill, Sandy Point", featured: false },
  { name: "Serendipity Restaurant & Lounge", category: "food_nightlife", description: "One of the most consistently praised restaurants on the island. Serendipity sits on a hillside above Basseterre with sweeping harbor views and a menu that moves confidently between Caribbean and international cuisine. The kind of place that earns its reputation through the food, not the marketing.", tip: "Reserve ahead for the terrace — the view over Basseterre Bay at sunset is one of the best tables on the island.", duration: "1.5–2.5 hours", lat: 17.2911, lng: -62.7336, area: "Fortlands, Basseterre", featured: false },
  { name: "Lion Rock Beach Bar", category: "food_nightlife", description: "A hidden gem with a loyal local following that has kept it well off the tourist radar. Cold drinks, fresh food, and zero pretension — the kind of place you stumble upon and end up staying three hours longer than you planned.", tip: "Getting there is half the adventure. No signage, no fuss.", duration: "1.5–3 hours", lat: 17.22900, lng: -62.63200, area: "Cockleshell Beach, Southeast Peninsula", featured: false },
  { name: "Shipwreck Beach Bar & Grill", category: "food_nightlife", description: "A South Friars Bay institution with 28 years of history — fishing nets, ramshackle decking, fresh jerk pork, grilled fish, and cold beers. Currently closed and pending relocation after the government issued an eviction order for South Friars Bay to make way for new development. Follow their socials for updates on where they land next.", tip: "Check their Facebook for relocation news. Worth finding whenever they reopen.", duration: "1.5–3 hours", lat: 17.229, lng: -62.632, area: "South Friars Bay (relocating)", featured: false, closedNote: "Temporarily closed — pending relocation from South Friars Bay. See: https://www.thestkittsnevisobserver.com/bar-operators-at-south-friars-bay-ordered-to-vacate-by-april-7/" },
  { name: "Discovery Beach Bar", category: "food_nightlife", description: "Consistently one of the highest-rated bars on the island — no gimmicks, just good drinks, fresh coconut shrimp, and ginger wings that people talk about long after leaving St Kitts. Currently closed and pending relocation after the South Friars Bay eviction order.", tip: "The coconut shrimp and ginger wings are the signature orders. Worth tracking down when they reopen.", duration: "1.5–3 hours", lat: 17.2295, lng: -62.6325, area: "South Friars Bay (relocating)", featured: false, closedNote: "Temporarily closed — pending relocation from South Friars Bay. See: https://www.thestkittsnevisobserver.com/bar-operators-at-south-friars-bay-ordered-to-vacate-by-april-7/" },
  { name: "Reef Bar and Grille", category: "food_nightlife", description: "A north coast gem in Dieppe Bay Town serving fresh Caribbean seafood and grilled dishes in a casual open-air setting. One of the few quality dining spots on the Atlantic side of the island and a great reason to make the drive up north.", tip: "Open Monday–Friday noon–9pm, Saturday–Sunday noon–midnight. Call ahead: +1 869-664-4434.", duration: "1.5–2.5 hours", lat: 17.416682, lng: -62.810482, area: "Dieppe Bay Town", featured: false },
  { name: "Ribeez BBQ", category: "food_nightlife", description: "St Kitts BBQ done properly. Ribeez has built a loyal following for their slow-smoked ribs, chicken, and sides that hit the spot every time. A no-frills operation where the food does all the talking.", tip: "Wed–Sat noon–6pm. Get there early — they sell out. Fort Thomas Road, Basseterre.", duration: "30–60 minutes", lat: 17.2906, lng: -62.7336, area: "Fortlands, Basseterre", featured: false },
  { name: "La Catrina", category: "food_nightlife", description: "A recently opened Mexican spot on the Frigate Bay Strip bringing something genuinely different to the St Kitts dining scene. Tacos, margaritas, and Latin flavor on the liveliest stretch of beach bar real estate on the island.", tip: "On the Strip — easy to find once you're in Frigate Bay.", duration: "1–2 hours", lat: 17.2822, lng: -62.6898, area: "The Strip, Frigate Bay", featured: false },
  { name: "Indian Summer", category: "food_nightlife", description: "The best Indian food experience on St Kitts — a proper sit-down restaurant on Zenway Boulevard in Frigate Bay serving authentic curries, tandoori dishes, and a full bar. Reliably excellent and consistently packed with locals who know what's good.", tip: "Tue–Thu 5–10pm, Fri–Sun lunch and dinner. Reservations recommended on weekends: +1 869-662-9222.", duration: "1–1.5 hours", lat: 17.286380, lng: -62.685357, area: "Frigate Bay", featured: false },
  { name: "Lotus", category: "food_nightlife", description: "Thai and Asian cuisine at The Retreat on Timothy Hill, Frigate Bay. A welcome addition to the island's dining scene with fresh flavors and a calm, comfortable setting that's a world away from the beach bar strip below.", tip: "Tue–Sun 11am–9pm, closed Mondays. +1 869-665-6677.", duration: "1–1.5 hours", lat: 17.282918, lng: -62.684988, area: "Timothy Hill, Frigate Bay", featured: false },
  { name: "Balai", category: "food_nightlife", description: "Filipino, Japanese, and Korean flavors under one roof at The Retreat on Timothy Hill. Balai brings Asian fusion cooking to St Kitts that you genuinely would not expect to find on a small Caribbean island — and it delivers.", tip: "In the same complex as Lotus at The Retreat. +1 869-767-5741.", duration: "1–1.5 hours", lat: 17.282918, lng: -62.684988, area: "Timothy Hill, Frigate Bay", featured: false },
  { name: "The Monkey Bar", category: "food_nightlife", description: "Mexican food and cold drinks right on the South Frigate Bay beach strip. A lively spot with a fun crowd, solid frozen margaritas, and the kind of beachfront energy that keeps you on one more drink longer than planned.", tip: "On The Strip — liveliest Thursday and Saturday nights. +1 869-762-3505.", duration: "1.5–3 hours", lat: 17.280855, lng: -62.687328, area: "The Strip, Frigate Bay", featured: false },
  { name: "Lovers Bar", category: "food_nightlife", description: "A local bar in Old Road Town — off the tourist circuit and proudly so. The kind of spot where regulars have their own stool and strangers get welcomed like they've been coming for years. Cold drinks, local vibes, real St Kitts.", tip: "Cash only. Don't overthink it.", duration: "1–2 hours", lat: 17.321372, lng: -62.802421, area: "Old Road Town", featured: false },
  { name: "D'Curry Q", category: "food_nightlife", description: "Caribbean curry and roti in Needsmust, near Kumar's grocery. A no-frills local spot serving the real thing — stewed meats, curry goat, provisions — at prices that make sense. The kind of place that feeds the neighbourhood and earns it.", tip: "Go at lunch. Follow the crowd.", duration: "30–60 minutes", lat: 17.3120, lng: -62.7113, area: "Needsmust, Basseterre", featured: false },
  { name: "Shawarma King", category: "food_nightlife", description: "Fast, good, and filling shawarma at the Bird Rock Food Court in Basseterre. A popular local lunch spot that keeps a loyal following for a reason — the wraps are loaded, the prices are right, and the line moves fast.", tip: "Mon–Sat 11am–10pm. Bird Rock Road, on the main road into Frigate Bay. +1 869-766-6709.", duration: "20–40 minutes", lat: 17.2950, lng: -62.7082, area: "Bird Rock, Basseterre", featured: false },
  { name: "Jasmine's Snackette", category: "food_nightlife", description: "A proper local snackette by the bus and ferry terminal in Basseterre — across from the ticket window where the real Basseterre street food scene lives. The kind of spot that feeds the city at lunch. Local food, local prices, no tourist markup.", tip: "Right across from the ferry ticket window at the terminal. Go at lunchtime.", duration: "20–40 minutes", lat: 17.2939, lng: -62.7260, area: "Ferry Terminal, Basseterre", featured: false },
  { name: "Arthur's", category: "food_nightlife", description: "A beloved Caribbean seafood institution on Dieppe Bay Beach on the north coast, serving fresh catch prepared simply and well. Arthur's has the kind of reputation that brings people back year after year — and makes the drive up the Atlantic coast worth every minute.", tip: "Wed–Sun noon–9pm. Cash preferred. +1 869-465-1004. Make the drive.", duration: "1.5–2.5 hours", lat: 17.417827, lng: -62.810566, area: "Dieppe Bay Beach", featured: false },
  // LOOT
  { name: "Amina Craft Market", category: "loot", description: "Right at Port Zante where cruise ships dock, Amina is the most accessible spot on the island for local crafts — colourful clothing, handmade gifts, and island-made souvenirs. It can get hectic on cruise days but the vendors are genuinely local and the goods are the real thing.", tip: "Go early on cruise days or skip to a quieter afternoon. Haggling is not expected but conversations are.", duration: "30–45 minutes", lat: 17.29500, lng: -62.72700, area: "Port Zante, Basseterre", featured: false },
  { name: "Caribelle Batik at Romney Manor", category: "loot", description: "The original. Caribelle Batik has been producing handcrafted batik fabrics at Romney Manor since 1974 — you can watch artisans work the wax-resist technique in the open studio before buying directly from the source. Sarongs, clothing, cushions, and wall art, all made on-site.", tip: "This is the only place to buy truly authentic Caribelle Batik — anything sold elsewhere is a copy.", duration: "45–75 minutes", lat: 17.31667, lng: -62.79444, area: "Old Road Town, Romney Manor", featured: false },
  { name: "The Shell Works", category: "loot", description: "A small, genuine workshop where artisans handcraft jewellery, boxes, and decorations from shells, driftwood, and local ocean materials. The kind of place you find by walking and remember forever.", tip: "There's often someone at work outside the shop — stop and watch before going in.", duration: "20–30 minutes", lat: 17.29191, lng: -62.7332, area: "Palm Court Gardens area, Basseterre", featured: false },
  { name: "Basseterre Public Market", category: "loot", description: "The real St Kitts. The central market in Basseterre is where locals shop for fresh produce, spices, hot sauce, bush tea, and street food. Pick up Mrs. Greaux pepper sauce, local guava cheese sweets, and fresh tamarind. Saturday morning is when it's fully alive.", tip: "Saturday before 9am is peak time. Come hungry.", duration: "30–60 minutes", lat: 17.29800, lng: -62.72400, area: "Central Basseterre", featured: false },
  // BEACHES
  { name: "Cockleshell Bay", category: "beach", description: "Widely considered the most beautiful beach on St Kitts, Cockleshell Bay is a long sweep of white sand with crystalline turquoise water and the dramatic cone of Nevis rising just three miles across the Narrows channel — a postcard view from every towel. ⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", tip: "Watersports like kayaking and paddleboarding can be rented from operators on the beach, and the snorkeling off the western rocks is excellent for beginners.", duration: "2–5 hours", lat: 17.22147, lng: -62.64087, area: "Southern tip, Southeast Peninsula", featured: true },
  { name: "Frigate Bay South (The Strip)", category: "beach", description: "South Frigate Bay is St Kitts's most social beach, a crescent of warm Caribbean sand lined with the legendary 'Strip' of beach bars. By day, calm turquoise water makes it a relaxed spot; by evening, the bars come alive with soca and reggae music, cold Carib beers, and the easy camaraderie of locals and visitors mingling until late. ⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", tip: "Mr. X's Shiggidy Shack anchors one end of the Strip and is the spot for Wednesday trivia nights and Saturday karaoke — don't miss it.", duration: "2–4 hours", lat: 17.26700, lng: -62.68300, area: "Frigate Bay, Caribbean side, The Strip", featured: false },
  { name: "Banana Bay Beach", category: "beach", description: "Curving gracefully next to Cockleshell Bay at the very tip of the Southeast Peninsula, Banana Bay is a stunning stretch of golden sand set against sculpted volcanic hills. The water is exceptional for snorkeling and swimming, with extraordinary clarity and a gentle swell. ⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", tip: "Beach-hop directly from Cockleshell Bay to Banana Bay on foot — they share an unbroken stretch of shoreline separated only by a short walk.", duration: "1–3 hours", lat: 17.22547, lng: -62.63882, area: "Southeast Peninsula tip", featured: false },
  { name: "Majors Bay", category: "beach", description: "A narrow, unspoiled strip of sand at the southern end of the Southeast Peninsula, Majors Bay is where the Nevis ferry departs from one end, while the rest of the beach remains beautifully undeveloped. A submerged shipwreck just offshore makes this one of the best and most accessible snorkeling spots on the island. ⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", tip: "Bring your own snorkel gear — the shipwreck off the beach is shallow and ideal for novice snorkelers with remarkable underwater visibility.", duration: "1–2 hours", lat: 17.22675, lng: -62.64924, area: "Southeast Peninsula, near Nevis ferry terminal", featured: false },
  { name: "South Friars Bay", category: "beach", description: "A gorgeous, crescent-shaped bay on the Caribbean side of the isthmus, South Friars Bay is one of the most scenic mid-island beaches with calm, clear water ideal for snorkeling along the rocky edges. The views across to Nevis are superb on a clear day. ⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", tip: "South Friars Bay is the beach you see from below as you descend Timothy Hill — pull over for the view before dropping down to swim.", duration: "1.5–3 hours", lat: 17.267, lng: -62.667, area: "Southeast isthmus, Caribbean side", featured: false },
  { name: "North Friars Bay", category: "beach", description: "Visible from Timothy Hill as you approach the peninsula, North Friars Bay is a quieter and less developed beach with rougher Atlantic water that appeals to those seeking solitude. The beach has no permanent facilities, attracting local surfers and beachcombers seeking shells and sea glass along the windswept shoreline. ⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", tip: "Strong currents and waves mean this beach is best for walking and photography rather than swimming.", duration: "30–45 minutes", lat: 17.27984, lng: -62.67546, area: "Southeast isthmus, Atlantic side", featured: false },
  { name: "White House Bay", category: "beach", description: "One of St Kitts's best-kept secrets, White House Bay is a secluded cove on the Southeast Peninsula with a rocky shore that rewards snorkelers with spectacular underwater topography — including a shallow shipwreck accessible to beginner snorkelers. ⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", tip: "The shipwreck here is arguably better than the one at Majors Bay for snorkeling — bring gear and allow at least an hour in the water.", duration: "1–2 hours", lat: 17.24815, lng: -62.65503, area: "Southeast Peninsula, Caribbean side", featured: false },
  { name: "Dieppe Bay Black Sand Beach", category: "beach", description: "On the northern Atlantic coast, Dieppe Bay marks the site of the first European settlement in the Eastern Caribbean and today retains a dramatic black volcanic sand beach rarely visited by tourists. The charming small town frames the beach with colorful wooden houses and fishing boats. ⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", tip: "The black sand here makes for extraordinary photographs, especially in the golden hour.", duration: "30–45 minutes", lat: 17.41484, lng: -62.81397, area: "Dieppe Bay Town, northern Atlantic coast", featured: false },
  { name: "Frigate Bay North (Atlantic Side)", category: "beach", description: "North Frigate Bay stretches along the Atlantic side of the isthmus, a long golden crescent of beach that is excellent for walking and kite-flying in the consistent trade winds. The water is more vigorous than the Caribbean side, making it the island's prime spot for wind sports. ⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", tip: "Exercise caution when swimming — Atlantic currents here can be strong and unpredictable.", duration: "1–3 hours", lat: 17.28000, lng: -62.67200, area: "Frigate Bay, Atlantic side", featured: false },
  { name: "Turtle Beach", category: "beach", description: "At the very end of a dirt road on the Southeast Peninsula, Turtle Beach faces 'The Narrows' channel separating St Kitts from Nevis, and offers excellent swimming in water that is warmer and calmer than many peninsula shores. On calm days you can see sea turtles feeding in the sea grass beds just offshore. ⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", tip: "The sea grass beds just off the beach attract resident sea turtles — swim quietly out to about 10 meters depth and keep still for the best chance of a sighting.", duration: "1–2 hours", lat: 17.23514, lng: -62.62758, area: "Southeast Peninsula, facing The Narrows toward Nevis", featured: false },
  { name: "Sandy Bank Bay", category: "beach", description: "Tucked on the Atlantic side of the Southeast Peninsula, Sandy Bank Bay is one of the most secluded and unspoiled beaches on St Kitts. Almost entirely undeveloped, the beach sees very few visitors even on the busiest cruise ship days. Sea glass is common along the tideline. ⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", tip: "Pack a picnic and plan to have this beach to yourself — there are no facilities here whatsoever, but the reward is total seclusion.", duration: "1–2 hours", lat: 17.24000, lng: -62.63000, area: "Southeast Peninsula, Atlantic side", featured: false },
  // SCENIC DRIVES
  { name: "Ring Road Circuit", category: "scenic_drive", description: "St Kitts's single main road loops around the entire northern portion of the island in a roughly 25-mile circuit, passing through fishing villages, sugar cane fields, plantation ruins, black sand beaches, and the lush foothills of Mount Liamuiga. The drive provides a complete cross-section of the island's landscapes, culture, and history in a single journey.", tip: "Drive counter-clockwise (northward from Basseterre along the Caribbean coast) for the best light in the morning and afternoon on historic stops.", duration: "Full day (5–7 hours with stops)", lat: 17.35000, lng: -62.76000, area: "Entire island; start/end at Basseterre", featured: true },
  { name: "Southeast Peninsula Road", category: "scenic_drive", description: "Completed in 1989, the Dr. Kennedy Simmonds Highway is one of the most dramatic coastal drives in the Eastern Caribbean, threading along the narrow spine of the Southeast Peninsula through rolling volcanic hills, emerald salt ponds, and stunning dual-ocean views.", tip: "Drive slowly and stop often — informal pulloffs throughout the peninsula offer views and short walks that are not signposted.", duration: "1.5–3 hours (with stops)", lat: 17.2700, lng: -62.6600, area: "Southeast Peninsula, Frigate Bay to Cockleshell Bay", featured: false },
  { name: "Basseterre to Old Road Heritage Route", category: "scenic_drive", description: "Heading west out of Basseterre along the Caribbean coast, this route passes through the island's historical heartland — the original sugar plantation belt. As the road winds through Challengers, Half Way Tree, and on to Old Road Town, ruins of great houses and windmill towers punctuate the sugarcane-lined road.", tip: "Combine this drive with stops at Wingfield Estate, Romney Manor, and Brimstone Hill — budget a full morning for this western corridor.", duration: "45 min to full day (with all stops)", lat: 17.30500, lng: -62.75000, area: "West coast, Basseterre to Old Road Town", featured: false },
  { name: "Timothy Hill Overlook Drive", category: "scenic_drive", description: "The short approach drive up to Timothy Hill is itself a spectacular experience, as the road crests the ridge and the land falls away on both sides revealing simultaneous sea views — the calm turquoise Caribbean to the west and the deeper blue Atlantic to the east.", tip: "The view is equally stunning in both directions — park and walk to the low stone wall on both sides of the road for the full panoramic effect.", duration: "15–20 minutes", lat: 17.2812, lng: -62.6789, area: "Southeast Peninsula Road, approaching Timothy Hill", featured: false },
];

const SEED_SALT_POSTS = [
  {
    title: "The Beaches Nobody Tells You About",
    date: "2026-04-01",
    preview: "Cockleshell is beautiful. You already know that. Every tourist brochure, every Instagram account, every hotel concierge — all pointing you to the same patch of sand. Here's what they don't tell you...",
    body: `Cockleshell is beautiful. You already know that. Every tourist brochure, every Instagram account, every hotel concierge — all pointing you to the same patch of sand. Here's what they don't tell you.\n\nWhite House Bay has a shipwreck you can swim to in about ten strokes. Sandy Bank Bay on the Atlantic side will give you sea glass and total silence and absolutely zero other people on a Tuesday. Majors Bay looks unremarkable from the road and is extraordinary from the water.\n\nThe rule on this island is simple: if it's easy to get to, it's crowded. If the road is a little rough, it's worth it. If your rental car company would prefer you didn't go there — that's exactly where you should go.\n\nYou're on a volcanic island in the Caribbean with a rental car. Stop following the signs.`,
    emoji: "🏖️",
    tag: "Beaches",
    visible: true,
  },
  {
    title: "How to Do the Frigate Bay Strip Right",
    date: "2026-03-19",
    preview: "People come to the Strip and leave saying it was fine. Fine. On an island with this much rum and this many stars overhead, fine is an unacceptable outcome. Here's how to not waste it.",
    body: `People come to the Strip and leave saying it was fine. Fine. On an island with this much rum and this many stars overhead, fine is an unacceptable outcome.\n\nFirst: don't arrive before 9pm on a weekend. You'll be sitting alone in a plastic chair staring at the sea wondering if you got the wrong night. You didn't. The island just runs late.\n\nSecond: don't commit to one bar. Walk the whole strip before you plant your flag. Each bar has its own energy on any given night.\n\nThird: Wednesday is Trivia Night at Shiggidy Shack. If you are on this island on a Wednesday and you do not go to trivia night, I cannot help you.\n\nFourth: the rum punch is not a decoration. Respect it.`,
    emoji: "🍹",
    tag: "Nightlife",
    visible: true,
  },
  {
    title: "The Music Festival Is Not Optional",
    date: "2026-02-10",
    preview: "Every June, Warner Park Stadium becomes one of the best music venues in the world for three nights. I'm not exaggerating. The lineup this year includes Steel Pulse and Fantasia. June 25–27.",
    body: `Every June, Warner Park Stadium becomes one of the best music venues in the world for three nights. I'm not exaggerating.\n\nThe St Kitts Music Festival has been running for 28 years. In that time it has hosted names that have no business playing an outdoor stadium on a Caribbean island of 50,000 people — and that is exactly what makes it extraordinary.\n\nThis year: Steel Pulse, Fantasia, and a lineup that fills out from there. June 25 to 27. Warner Park.\n\nA few things to know: Night 3 is always the best night. The food outside the stadium gates is better than inside. Arrive later than you think you should. Leave later than you planned to.\n\nAnd if you're still in your hotel room at 10pm telling yourself you'll go next year — next year you'll say the same thing. Go this year.`,
    emoji: "🎵",
    tag: "Events",
    visible: true,
  },
  {
    title: "Stop Renting a Scooter. Get a Jeep.",
    date: "2026-01-22",
    preview: "I run a rental car company. I'm biased. But I'm also right. The Southeast Peninsula road, the drive up to Brimstone Hill, the back road to Dieppe Bay — none of these are scooter roads.",
    body: `I run a rental car company. I'm biased. But I'm also right.\n\nSt Kitts is a small island with a big road network and some of it is emphatically not designed for scooters. The Southeast Peninsula road is incredible — winding up over volcanic ridges with the Caribbean on one side and the Atlantic on the other — and it will eat a scooter and its rider without remorse if the wind gets involved.\n\nThe back road to Dieppe Bay, the agricultural tracks near Old Road, the drive up to Wingfield Estate — these demand four wheels and a little confidence.\n\nGet a Jeep. Roll the windows down. Do the Ring Road circuit counter-clockwise starting before 8am. Pull over every time you see a view worth stopping for.\n\nThe island is small enough that you can cover all of it in a day. Large enough that you'll want to do it twice.`,
    emoji: "🚙",
    tag: "Getting Around",
    visible: true,
  },
];

export async function registerRoutes(httpServer: Server, app: Express): Promise<Server> {
  // ── Seed / reseed on every boot ────────────────────────
  // Always wipe and reseed stops so code changes are reflected immediately
  storage.deleteAllStops();
  for (const stop of SEED_STOPS) {
    storage.createStop({ ...stop, visible: true } as any);
  }

  const existingPosts = storage.getAllSaltPosts();
  if (existingPosts.length === 0) {
    for (const post of SEED_SALT_POSTS) {
      storage.createSaltPost(post as any);
    }
  }

  // ── Public API ─────────────────────────────────────────
  app.get("/api/stops", (req, res) => {
    const { category } = req.query;
    if (category && typeof category === "string" && category !== "all") {
      return res.json(storage.getStopsByCategory(category));
    }
    return res.json(storage.getVisibleStops());
  });

  app.get("/api/stops/:id", (req, res) => {
    const id = parseInt(req.params.id);
    const stop = storage.getStop(id);
    if (!stop) return res.status(404).json({ message: "Stop not found" });
    return res.json(stop);
  });

  app.get("/api/salt-posts", (_req, res) => {
    return res.json(storage.getVisibleSaltPosts());
  });

  // ── Admin auth ─────────────────────────────────────────
  app.post("/api/admin/login", (req, res) => {
    const { password } = req.body;
    if (password === ADMIN_PASSWORD) {
      return res.json({ ok: true });
    }
    return res.status(401).json({ message: "Wrong password" });
  });

  // ── Admin: Stops CRUD ──────────────────────────────────
  app.get("/api/admin/stops", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    return res.json(storage.getAllStops());
  });

  app.post("/api/admin/stops", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    const stop = storage.createStop(req.body);
    return res.json(stop);
  });

  app.put("/api/admin/stops/:id", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    const id = parseInt(req.params.id);
    const stop = storage.updateStop(id, req.body);
    if (!stop) return res.status(404).json({ message: "Stop not found" });
    return res.json(stop);
  });

  app.delete("/api/admin/stops/:id", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    storage.deleteStop(parseInt(req.params.id));
    return res.json({ ok: true });
  });

  // ── Admin: Salt Posts CRUD ─────────────────────────────
  app.get("/api/admin/salt-posts", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    return res.json(storage.getAllSaltPosts());
  });

  app.post("/api/admin/salt-posts", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    const post = storage.createSaltPost(req.body);
    return res.json(post);
  });

  app.put("/api/admin/salt-posts/:id", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    const id = parseInt(req.params.id);
    const post = storage.updateSaltPost(id, req.body);
    if (!post) return res.status(404).json({ message: "Post not found" });
    return res.json(post);
  });

  app.delete("/api/admin/salt-posts/:id", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    storage.deleteSaltPost(parseInt(req.params.id));
    return res.json({ ok: true });
  });

  return httpServer;
}

function checkAdmin(req: any): boolean {
  const auth = req.headers["x-admin-password"];
  return auth === ADMIN_PASSWORD;
}
