import type { Express } from "express";
import type { Server } from "http";
import { storage } from "./storage";
import Database from "better-sqlite3";
import path from "path";
const sqlite = new Database(path.join(process.cwd(), "stkitts.db"));

const ADMIN_PASSWORD = "salty2026";

const SEED_STOPS = [
  // HISTORICAL
  { name: "Brimstone Hill Fortress", category: "historical", description: "Dubbed the Gibraltar of the Caribbean, this UNESCO World Heritage Site is one of the best-preserved fortress complexes in the Americas. Built over a century by enslaved Africans under British military direction, it crowns a 972-foot volcanic hill with sweeping views across the Caribbean Sea to neighboring islands. Took over 100 years to complete and was considered impregnable by 1780.", tip: "Arrive early morning before the cruise ship crowds. The views from the citadel at sunrise are unreal.", duration: "2–3 hours", lat: 17.3469, lng: -62.8364, area: "Sandy Point", featured: true },
  { name: "Romney Manor & Caribelle Batik", category: "historical", description: "A 17th-century estate once linked to the family of Thomas Jefferson, now home to Caribelle Batik — a working studio where artisans handcraft vivid fabrics using centuries-old wax-resist techniques. Eight acres of botanical gardens surround the Great House, anchored by a magnificent 400-year-old saman tree said to be the largest living organism on the island.", tip: "Watch the batik artists at work for free. The studios are open and the fabrics are the real deal.", duration: "1–1.5 hours", lat: 17.3257672, lng: -62.8036333, area: "Old Road", featured: false },
  { name: "Wingfield Estate Sugar Plantation Ruins", category: "historical", description: "The oldest sugar estate and rum distillery ruins in the Eastern Caribbean, dating to the early 1600s. Among the crumbling stone mills, ancient Kalinago petroglyphs carved over 2,000 years ago can still be found on boulders at the edge of the rainforest. An active archaeological excavation means the site keeps revealing more.", tip: "⚠️ We always recommend hiring a local guide for hikes in St Kitts. Ask about the petroglyphs — easy to miss on your own.", duration: "45–90 minutes", lat: 17.3267658, lng: -62.8027911, area: "Old Road", featured: false },
  { name: "Independence Square", category: "historical", description: "The historic heart of Basseterre. This leafy colonial square served as the administrative, commercial, and social center of the island from the 1750s — and for a period, a slave market. Where the fountain stands today, enslaved people were once sold. Renamed on September 19, 1983, the day St Kitts gained independence.", tip: "Best photographed in early morning light. Liveliest on weekend mornings when locals gather.", duration: "20–30 minutes", lat: 17.2966337, lng: -62.7276168, area: "Basseterre", featured: false },
  { name: "The Circus & Berkeley Memorial", category: "historical", description: "The commercial heart of Basseterre, modeled on London's Piccadilly Circus. The Victorian-era Berkeley Memorial — a green cast-iron clock tower and drinking fountain built in 1883 — anchors the roundabout. Locals call it Little Ben. Its four faces each point down one of the city's main streets.", tip: "The upper floor of the bakery on the Circus gives you a perfect overhead angle on the memorial.", duration: "15–20 minutes", lat: 17.2953405, lng: -62.7250856, area: "Basseterre", featured: false },
  { name: "St George's Anglican Church", category: "historical", description: "The largest church in Basseterre, standing at the head of Church Street. Rebuilt multiple times after fires and hurricanes — most recently after Hurricane Hugo in 1989. The graveyard contains headstones dating back to the 1600s. Entry is free and the grounds are open during daylight hours.", tip: "Look for the oldest grave markers in the far corners of the cemetery.", duration: "20–30 minutes", lat: 17.2975111, lng: -62.7258933, area: "Basseterre", featured: false },
  { name: "Immaculate Conception Co-Cathedral", category: "historical", description: "A striking Roman Catholic cathedral with twin towers dominating the eastern side of Independence Square. The current structure was completed in 1928 and elevated to co-cathedral status in 1981. The grey stone exterior and ornate interior reflect the island's French and British colonial heritage. Cool, quiet, and beautiful inside.", tip: "Particularly striking at dusk when the setting sun hits the stonework.", duration: "15–20 minutes", lat: 17.2964244, lng: -62.7230564, area: "Basseterre", featured: false },
  { name: "Old Road Bay & Town", category: "historical", description: "This small fishing village marks the exact spot where Sir Thomas Warner landed in 1623 to establish the first permanent British settlement in the Caribbean. The unhurried village retains its weathered character with colorful fishing boats drawn up on the shore. One of the most historically significant sites in the entire Caribbean — and most visitors drive right past it.", tip: "Stop at the historical marker near the bay before heading to Wingfield Estate nearby.", duration: "30–45 minutes", lat: 17.3154972, lng: -62.7991118, area: "Old Road", featured: false },
  { name: "Fairview Great House & Botanical Gardens", category: "historical", description: "The only surviving French colonial plantation great house on St Kitts, built circa 1701 to house French military officers. Fully restored and furnished with period antiques, surrounded by meticulously maintained tropical botanical gardens. A rare piece of French colonial architecture on an otherwise British-dominated island.", tip: "Fairview occasionally hosts candlelit dinners on the veranda — worth checking the schedule.", duration: "1–1.5 hours", lat: 17.3015279, lng: -62.7731648, area: "Boyd's", featured: false },
  { name: "National Museum of St Kitts", category: "historical", description: "Housed in the 1894 Old Treasury Building near Port Zante, this museum covers the full arc of Kittitian history — from pre-Columbian Kalinago settlement through slavery, emancipation, the sugar economy, and independence. Compact enough to tour in an hour. Entry around USD $5. The best single place to understand the island before you explore it.", tip: "Make this your first stop on any Basseterre walking tour. The context makes every other site hit different.", duration: "45–75 minutes", lat: 17.2945712, lng: -62.726305, area: "Basseterre", featured: false },
  { name: "Port Zante & Basseterre Waterfront", category: "historical", description: "The cruise pier sits at the heart of Basseterre with walking access to the Circus, Independence Square, and the National Museum. The waterfront promenade offers views across the harbor to Nevis. A solid starting point for a walking tour of the capital even if you are not arriving by ship.", tip: "Grab a coconut water from a street vendor before heading into town.", duration: "30–45 minutes", lat: 17.2935199, lng: -62.7262531, area: "Basseterre", featured: false },
  { name: "Bloody Point", category: "historical", description: "In 1626, English and French colonists united to massacre an estimated 2,000 Kalinago people at this site, ending indigenous resistance to European colonization of St Kitts. The river that once ran red with blood gave this place its name. One of the most consequential and disturbing sites in Caribbean colonial history. It deserves to be known.", tip: "No formal visitor infrastructure — it is a roadside site. Pull over, read the history, let it land.", duration: "15–20 minutes", lat: 17.3052838, lng: -62.7889464, area: "Old Road", featured: false },
  { name: "Sir Thomas Warner Gravestone", category: "historical", description: "In the churchyard of St Thomas Middle Island Church lies the grave of Sir Thomas Warner, the first English governor of the West Indies and founder of the British settlement on St Kitts in 1623. Beside him is the grave of Samuel Jefferson — great-grandfather of US President Thomas Jefferson. This modest churchyard holds the remains of people who shaped the entire hemisphere.", tip: "The grave markers are simple and easy to miss. Take a moment with it.", duration: "15–20 minutes", lat: 17.3275, lng: -62.8138, area: "Middle Island", featured: false },
  { name: "Kalinago Rock Petroglyphs", category: "historical", description: "Ancient carvings made by the Kalinago people more than 2,000 years ago, etched into boulders near Wingfield Estate at the edge of the rainforest. Believed to express the religious beliefs and ceremonial practices of the indigenous people who inhabited these islands long before European contact. A quiet and powerful reminder of who was here first.", tip: "⚠️ We always recommend hiring a local guide for hikes in St Kitts. Easy to miss without someone who knows where to look.", duration: "30–45 minutes", lat: 17.3228726, lng: -62.8059023, area: "Old Road", featured: false },
  { name: "Old Road Rum Distillery", category: "historical", description: "The oldest surviving rum distillery on St Kitts, rooted in the island's centuries-long sugar and rum heritage. Visitors can tour the distillery, learn about the production process, and make a personalized bottle. Rum is not just a drink here — it is the liquid history of the island's sugar economy, colonial labor, and Kittitian identity.", tip: "The hands-on bottle-making experience is worth doing. Book ahead during cruise ship season.", duration: "1–1.5 hours", lat: 17.327098, lng: -62.8021778, area: "Old Road", featured: false },
  { name: "The War Memorial & Cenotaph", category: "historical", description: "Located in Fortlands at the end of Bay Road, this cenotaph was unveiled by Princess Margaret in 1955 with two brass plaques commemorating Kittitians who served and died in both World Wars. A modest but moving monument to the men and women of this small island who went to fight in conflicts on the other side of the world.", tip: "Most visitors drive past without stopping. It deserves a moment.", duration: "10–15 minutes", lat: 17.2924502, lng: -62.7335707, area: "Basseterre", featured: false },
  { name: "St Kitts Scenic Railway", category: "historical", description: "The last surviving railway in the Eastern Caribbean, originally built between 1912 and 1926 to haul sugarcane from the fields to the central sugar factory in Basseterre. Today it operates as a heritage tour on a narrow-gauge track that circles roughly two-thirds of the island on a scenic double-decker train through villages, coastline, and former plantation land.", tip: "Book in advance — tour groups fill this up fast. The upper deck gives the best views.", duration: "3–3.5 hours", lat: 17.3131903, lng: -62.7140392, area: "Basseterre", featured: false },
  { name: "Old Treasury Building", category: "historical", description: "Constructed in 1894 from hand-cut blocks of local volcanic andesite stone, the Old Treasury Building is one of the most architecturally significant structures in Basseterre. Its iconic archway once served as the entry portal for passengers arriving by ship, and the dome on top functioned as a lighthouse. Now houses the National Museum and the St Christopher National Trust.", tip: "The building itself is the exhibit. Walk through the archway and look up — the stonework is extraordinary.", duration: "15–20 minutes", lat: 17.2956, lng: -62.7227, area: "Basseterre", featured: false },
  { name: "Shadwell Great House", category: "historical", description: "One of St Kitts' lesser-known but historically significant plantation great houses, sitting on the eastern side of the island away from the main tourist circuit. The estate dates to the colonial sugar era and the ruins and surrounding landscape offer a raw, unpolished look at plantation history without the crowds found at more well-known sites.", tip: "Not on the standard tour circuit — which is exactly why it is worth finding.", duration: "30–45 minutes", lat: 17.3066, lng: -62.7357, area: "Eastside", featured: false },
  // THE BUSH (nature)







  // LIME & DINE
  { name: "Mr. X's Shiggidy Shack", category: "food_nightlife", description: "The most beloved beach bar on The Strip at South Frigate Bay. Cold Caribs, killer rum punches, and good vibes that make you miss your flight home. Wednesday nights are legendary for trivia, Thursday nights bring the famous buffet, and Saturdays go late with karaoke. This is the move.", tip: "Wednesday Trivia Night is a must — the host is hilarious, the crowd is mixed local and tourist, and teams get seriously competitive.", duration: "2–4 hours", lat: 17.2809353, lng: -62.6883142, area: "The Strip, Frigate Bay", featured: true },
  { name: "Sprat Net Bar & Grill", category: "food_nightlife", description: "One of the most authentic local dining experiences on St Kitts. A rustic open-air pavilion at Old Road Bay where you pick your own fish from the display and watch it grilled to order, served with corn, potatoes, and Johnny cakes. On Wednesday and Saturday nights, live Caribbean bands fill the air under the stars.", tip: "Wednesday nights feature the best live music on this side of the island — the scene is lively, local, and completely unpretentious.", duration: "1.5–3 hours", lat: 17.3200589, lng: -62.8033783, area: "Old Road Town", featured: false },
  { name: "El Fredo's", category: "food_nightlife", description: "A proper local spot in Basseterre that doesn't advertise to tourists — and that's exactly why you should go. Some of the best BBQ ribs on the island alongside rice and peas, stewed chicken, and whatever the kitchen feels like cooking that day. The kind of place where the food is made by someone's grandmother.", tip: "Cash only. Portions are generous and things run out. Go before 1pm.", duration: "45–75 minutes", lat: 17.2948039, lng: -62.7194302, area: "Basseterre", featured: false },
  { name: "17\u00b062\u00b0 Gibraltar Gastrolounge", category: "food_nightlife", description: "Perched on top of Brimstone Hill Fortress — a UNESCO World Heritage Site — this is one of the most dramatically located restaurants in the entire Caribbean. Chef O'Keeffe Marshall's menu covers New American, Caribbean, and Thai fusion territory built around locally sourced ingredients. The views are ridiculous. The cocktails are serious.", tip: "Open daily 11am–4pm. Book ahead — it fills up fast on cruise ship days.", duration: "1.5–2.5 hours", lat: 17.3471402, lng: -62.8373881, area: "Brimstone Hill, Sandy Point", featured: false },
  { name: "Serendipity Restaurant & Lounge", category: "food_nightlife", description: "One of the most consistently praised restaurants on the island. Serendipity sits on a hillside above Basseterre with sweeping harbor views and a menu that moves confidently between Caribbean and international cuisine. The kind of place that earns its reputation through the food, not the marketing.", tip: "Reserve ahead for the terrace — the view over Basseterre Bay at sunset is one of the best tables on the island.", duration: "1.5–2.5 hours", lat: 17.2907408, lng: -62.7346817, area: "Fortlands, Basseterre", featured: false },
  { name: "Lion Rock Beach Bar", category: "food_nightlife", description: "A hidden gem with a loyal local following that has kept it well off the tourist radar. Cold drinks, fresh food, and zero pretension — the kind of place you stumble upon and end up staying three hours longer than you planned.", tip: "Getting there is half the adventure. No signage, no fuss.", duration: "1.5–3 hours", lat: 17.2296408, lng: -62.6366251, area: "Cockleshell Beach, Southeast Peninsula", featured: false },
  { name: "Shipwreck Beach Bar & Grill", category: "food_nightlife", description: "A South Friars Bay institution with 28 years of history — fishing nets, ramshackle decking, fresh jerk pork, grilled fish, and cold beers. Currently closed and pending relocation after the government issued an eviction order for South Friars Bay to make way for new development. Follow their socials for updates on where they land next.", tip: "Check their Facebook for relocation news. Worth finding whenever they reopen.", duration: "1.5–3 hours", lat: 17.229, lng: -62.632, area: "South Friars Bay (relocating)", featured: false, closedNote: "Temporarily closed — pending relocation from South Friars Bay. See: https://www.thestkittsnevisobserver.com/bar-operators-at-south-friars-bay-ordered-to-vacate-by-april-7/" },
  { name: "Discovery Beach Bar", category: "food_nightlife", description: "Consistently one of the highest-rated bars on the island — no gimmicks, just good drinks, fresh coconut shrimp, and ginger wings that people talk about long after leaving St Kitts. Currently closed and pending relocation after the South Friars Bay eviction order.", tip: "The coconut shrimp and ginger wings are the signature orders. Worth tracking down when they reopen.", duration: "1.5–3 hours", lat: 17.2295, lng: -62.6325, area: "South Friars Bay (relocating)", featured: false, closedNote: "Temporarily closed — pending relocation from South Friars Bay. See: https://www.thestkittsnevisobserver.com/bar-operators-at-south-friars-bay-ordered-to-vacate-by-april-7/" },
  { name: "Reef Bar and Grille", category: "food_nightlife", description: "A north coast gem in Dieppe Bay Town serving fresh Caribbean seafood and grilled dishes in a casual open-air setting. One of the few quality dining spots on the Atlantic side of the island and a great reason to make the drive up north.", tip: "Open Monday–Friday noon–9pm, Saturday–Sunday noon–midnight. Call ahead: +1 869-664-4434.", duration: "1.5–2.5 hours", lat: 17.4171944, lng: -62.8111846, area: "Dieppe Bay Town", featured: false },
  { name: "Ribeez BBQ", category: "food_nightlife", description: "St Kitts BBQ done properly. Ribeez has built a loyal following for their slow-smoked ribs, chicken, and sides that hit the spot every time. A no-frills operation where the food does all the talking.", tip: "Wed–Sat noon–6pm. Get there early — they sell out. Fort Thomas Road, Basseterre.", duration: "30–60 minutes", lat: 17.2903075, lng: -62.734176, area: "Fortlands, Basseterre", featured: false },
  { name: "La Catrina", category: "food_nightlife", description: "A recently opened Mexican spot on the Frigate Bay Strip bringing something genuinely different to the St Kitts dining scene. Tacos, margaritas, and Latin flavor on the liveliest stretch of beach bar real estate on the island.", tip: "On the Strip — easy to find once you're in Frigate Bay.", duration: "1–2 hours", lat: 17.2816477, lng: -62.6918716, area: "The Strip, Frigate Bay", featured: false },
  { name: "Indian Summer", category: "food_nightlife", description: "The best Indian food experience on St Kitts — a proper sit-down restaurant on Zenway Boulevard in Frigate Bay serving authentic curries, tandoori dishes, and a full bar. Reliably excellent and consistently packed with locals who know what's good.", tip: "Tue–Thu 5–10pm, Fri–Sun lunch and dinner. Reservations recommended on weekends: +1 869-662-9222.", duration: "1–1.5 hours", lat: 17.284311, lng: -62.6924296, area: "Frigate Bay", featured: false },
  { name: "Lotus", category: "food_nightlife", description: "Thai and Asian cuisine at The Retreat on Timothy Hill, Frigate Bay. A welcome addition to the island's dining scene with fresh flavors and a calm, comfortable setting that's a world away from the beach bar strip below.", tip: "Tue–Sun 11am–9pm, closed Mondays. +1 869-665-6677.", duration: "1–1.5 hours", lat: 17.2829454, lng: -62.687561, area: "Timothy Hill, Frigate Bay", featured: false },
  { name: "Balai", category: "food_nightlife", description: "Filipino, Japanese, and Korean flavors under one roof at The Retreat on Timothy Hill. Balai brings Asian fusion cooking to St Kitts that you genuinely would not expect to find on a small Caribbean island — and it delivers.", tip: "In the same complex as Lotus at The Retreat. +1 869-767-5741.", duration: "1–1.5 hours", lat: 17.2827012, lng: -62.6864852, area: "Timothy Hill, Frigate Bay", featured: false },
  { name: "The Monkey Bar", category: "food_nightlife", description: "Mexican food and cold drinks right on the South Frigate Bay beach strip. A lively spot with a fun crowd, solid frozen margaritas, and the kind of beachfront energy that keeps you on one more drink longer than planned.", tip: "On The Strip — liveliest Thursday and Saturday nights. +1 869-762-3505.", duration: "1.5–3 hours", lat: 17.2810015, lng: -62.6880069, area: "The Strip, Frigate Bay", featured: false },
  { name: "Lovers Bar", category: "food_nightlife", description: "A local bar in Old Road Town — off the tourist circuit and proudly so. The kind of spot where regulars have their own stool and strangers get welcomed like they've been coming for years. Cold drinks, local vibes, real St Kitts.", tip: "Cash only. Don't overthink it.", duration: "1–2 hours", lat: 17.321687, lng: -62.802957, area: "Old Road Town", featured: false },
  { name: "D'Curry Q", category: "food_nightlife", description: "Caribbean curry and roti in Needsmust, near Kumar's grocery. A no-frills local spot serving the real thing — stewed meats, curry goat, provisions — at prices that make sense. The kind of place that feeds the neighbourhood and earns it.", tip: "Go at lunch. Follow the crowd.", duration: "30–60 minutes", lat: 17.3091225, lng: -62.7132138, area: "Needsmust, Basseterre", featured: false },
  { name: "Shawarma King", category: "food_nightlife", description: "Fast, good, and filling shawarma at the Bird Rock Food Court in Basseterre. A popular local lunch spot that keeps a loyal following for a reason — the wraps are loaded, the prices are right, and the line moves fast.", tip: "Mon–Sat 11am–10pm. Bird Rock Road, on the main road into Frigate Bay. +1 869-766-6709.", duration: "20–40 minutes", lat: 17.2852516, lng: -62.6909974, area: "Bird Rock, Basseterre", featured: false },
  { name: "Jasmine's Snackette", category: "food_nightlife", description: "A proper local snackette by the bus and ferry terminal in Basseterre — across from the ticket window where the real Basseterre street food scene lives. The kind of spot that feeds the city at lunch. Local food, local prices, no tourist markup.", tip: "Right across from the ferry ticket window at the terminal. Go at lunchtime.", duration: "20–40 minutes", lat: 17.293861111111113, lng: -62.726194444444445, area: "Ferry Terminal, Basseterre", featured: false },
  { name: "Arthur's", category: "food_nightlife", description: "A beloved Caribbean seafood institution on Dieppe Bay Beach on the north coast, serving fresh catch prepared simply and well. Arthur's has the kind of reputation that brings people back year after year — and makes the drive up the Atlantic coast worth every minute.", tip: "Wed–Sun noon–9pm. Cash preferred. +1 869-465-1004. Make the drive.", duration: "1.5–2.5 hours", lat: 17.4180718, lng: -62.811787, area: "Dieppe Bay Beach", featured: false },
  // LOOT
  { name: "Ram's Supermarket — Bay Road", category: "loot", duration: "30–60 minutes", description: "The original. Ram's Bay Road has been feeding Basseterre since 1960 — the first self-service supermarket in the Federation and still the community favourite. Full grocery selection, produce, household goods, the works.", tip: "Mon–Thu 8am–7pm · Fri & Sat 8am–8pm · Sun 9am–2pm. Bay Road, central Basseterre.", lat: 17.2953635, lng: -62.7300319, area: "Central Basseterre", featured: false, parking: "Street parking available", kidsOk: "Yes", wifi: "No" },
  { name: "Ram's Supermarket — Bird Rock", category: "loot", duration: "30–60 minutes", description: "Just on the outskirts of central Basseterre, Ram's Bird Rock is the easy stop if you're heading toward Frigate Bay. Same full grocery range as Bay Road with slightly easier parking.", tip: "Mon–Sat 8am–8pm · Sun 9am–2pm. Bird Rock Road.", lat: 17.2963568, lng: -62.7129517, area: "Bird Rock, Basseterre", featured: false, parking: "Yes", kidsOk: "Yes", wifi: "No" },
  { name: "Ram's Supermarket — Buckley's", category: "loot", duration: "30–60 minutes", description: "The newest full-size Ram's, opened 2017 and serving the western part of the island. Modern layout, solid selection, and the longest weekday evening hours of the grocery locations. Won Basseterre Supermarket of the Year in 2018.", tip: "Mon–Sat 8am–9pm · Sun 9am–5pm. Buckley's, west of Basseterre.", lat: 17.2968251, lng: -62.7452236, area: "Basseterre", featured: false, parking: "Yes", kidsOk: "Yes", wifi: "No" },
  { name: "Ram's Express + Smoke N' Booze — Royal Plaza, Frigate Bay", category: "loot", duration: "15–30 minutes", description: "The most convenient stop if you're based in Frigate Bay. Open later than any other Ram's location — 10pm every night of the week. Duty free liquor, cigarettes, cigars, and a solid grocery/convenience selection. This is your go-to for rum and smokes on the strip.", tip: "Mon–Sun 8am–10pm. Royal Plaza, Frigate Bay strip. Best hours on the island for late-night supplies.", lat: 17.2909899, lng: -62.6873169, area: "Frigate Bay", featured: true, parking: "Yes", smoking: "Cigarettes & cigars sold here", kidsOk: "Yes", wifi: "No" },
  { name: "Ram's Smoke N' Booze — Atlantic View Plaza, Frigate Bay", category: "loot", duration: "15–30 minutes", description: "The relocated duty free liquor and tobacco shop, moved from Sugar Bay Club in late 2025 to the Atlantic View Plaza. Widest selection of duty free premium spirits, cigarettes, tobacco, and guaranteed authentic Cuban cigars in St Kitts. This is the one for serious bottle shopping.", tip: "Relocated from Sugar Bay Club in November 2025. Atlantic View Plaza, Frigate Bay. Call ahead to confirm current hours.", lat: 17.2907739, lng: -62.6951708, area: "Frigate Bay", featured: false, parking: "Yes", smoking: "Full duty free tobacco selection including Cuban cigars", kidsOk: "Yes", wifi: "No" },
  { name: "Port Zante", category: "loot", duration: "1–2 hours", description: "The cruise ship terminal in Basseterre. Duty free jewellery, watches, liquor, souvenir shops, and the usual tourist stuff. If you need a fridge magnet or a rum cake in a tin, this is your spot. Not where locals shop, but it's convenient and it's all in one place.", tip: "Open on cruise ship days. If there's no ship in port, most of it is closed.", lat: 17.2935199, lng: -62.7262531, area: "Port Zante, Basseterre", featured: false, parking: "Limited", kidsOk: "Yes", wifi: "No" },
  { name: "Ram's Smoke N' Booze — Port Zante", category: "loot", duration: "15–30 minutes", description: "Duty free liquor and tobacco right at the cruise terminal in Port Zante. Convenient if you're catching the ferry or picking someone up at the port. Same duty free pricing as the Frigate Bay locations.", tip: "Port Zante, Basseterre waterfront. Hours follow cruise ship schedule — call ahead if no ships are in port.", lat: 17.2935199, lng: -62.7262531, area: "Port Zante, Basseterre", featured: false, parking: "Limited", smoking: "Duty free tobacco and spirits", kidsOk: "Yes", wifi: "No" },
  { name: "Ram's Camps (Cash & Carry)", category: "loot", duration: "30–60 minutes", description: "Think of it as St Kitts' version of Costco. Ram's Cash & Carry in Bird Rock is where you go to buy in bulk — seafood, poultry, snacks, drinks, fruits, vegetables, and a solid range of household and kitchen goods. If you're stocking a villa, a boat, or just like buying smart, this is your spot.", tip: "Mon–Thu 8am–6pm · Fri–Sat 8am–7pm · Sun 9am–2pm. Bird Rock, St Kitts.", lat: 17.2953311, lng: -62.7092703, area: "Bird Rock, Basseterre", featured: false, parking: "Yes", kidsOk: "Yes", wifi: "No" },
  { name: "Carib Brewery", category: "loot", duration: "1.5–2 hours", description: "The island's beer, brewed right here in St Kitts. Tours take you through the full production process from grain to glass, ending exactly where it should — cold samples fresh off the line. This is one of those experiences tourists love more than they expected to, and locals are quietly proud of.", tip: "Mon–Fri 8am–4:30pm · Sat 8am–4pm. Call ahead to book a tour. Bring cash.", lat: 17.2964087, lng: -62.7394179, area: "Basseterre", featured: false, parking: "Yes", kidsOk: "No", wifi: "No" },
  { name: "SK & Sons", category: "loot", duration: "Online order", description: "Restaurant-quality specialty foods delivered to your door — seafood, premium meats, specialty frozen goods, and hard-to-find items you won't see at the regular supermarkets. Delivery only. They cover St Kitts and Nevis.", tip: "Order online at shopsksons.com — stock varies so check the site first. Prices in EC dollars. No storefront.", lat: 17.2927419, lng: -62.7088053, area: "Island-wide (Delivery)", featured: false, parking: "N/A", kidsOk: "Yes", wifi: "No" },
  { name: "Mix Italia", category: "loot", duration: "Online order", description: "Italian food and beverage importer delivering across the Caribbean. If you're cooking and want proper Italian ingredients — imported pasta, cheeses, cold cuts, olive oils, balsamic, truffle products, gelato bases — this is where to go. The kind of place you don't expect to find on a small island.", tip: "Delivery and order-based. Contact via mixitalia.com to arrange. No walk-in storefront.", lat: 17.2849737, lng: -62.6860668, area: "Island-wide (Delivery)", featured: false, parking: "N/A", kidsOk: "Yes", wifi: "No" },


  // NEW STOPS
  { name: "Washing Machine", category: "historical", duration: "30–60 minutes", description: "A dramatic natural rock formation on the northwest coast where Atlantic swells crash into volcanic channels creating a powerful churning effect — locals call it the Washing Machine. One of the most raw and photogenic spots on the island.", tip: "Stay back from the edge — the swells are unpredictable. Best at high tide for the full effect.", lat: 17.398671, lng: -62.8578472, area: "Northwest St Kitts", featured: false },
  { name: "St Kitts Eco Park", category: "historical", duration: "1–2 hours", description: "A sustainability-focused attraction on the northwest coast showcasing St Kitts' renewable energy and conservation efforts. Zip lines, nature trails, and views over the Atlantic and Caribbean simultaneously.", tip: "Check opening hours before visiting. Good for families.", lat: 17.3753474, lng: -62.8575897, area: "Northwest St Kitts", featured: false },
  { name: "St John's Church", category: "historical", duration: "20–30 minutes", description: "One of the oldest Anglican churches on the island, located on the north coast near Dieppe Bay. The churchyard contains some of the earliest colonial-era grave markers in the Federation — a quiet and overlooked piece of island history.", tip: "Worth a stop if you're driving the north coast. Respectful dress appreciated.", lat: 17.4035762, lng: -62.7906467, area: "Dieppe Bay", featured: false },
  { name: "Timothy Hill Overlook", category: "historical", duration: "15–30 minutes", description: "The ridge between Frigate Bay and the Southeast Peninsula — one of the most photographed viewpoints in St Kitts. On a clear day you can see both the Caribbean and Atlantic simultaneously, with Nevis directly south. The drive up is half the experience.", tip: "Pull off safely and walk to the edge. Sunset here is worth planning around.", lat: 17.2812346, lng: -62.683991, area: "Southeast Peninsula", featured: true },
  { name: "Belle Mont Farm / Kittitian Hill", category: "historical", duration: "1–2 hours", description: "An eco-luxury estate on the slopes of Mount Liamuiga that has become one of the most recognised properties in the Caribbean. The architecture, the farm-to-table concept, and the views make it worth a visit even if you're not staying. The farm itself supplies the restaurant with produce grown on-site.", tip: "Non-guests can visit the farm and restaurant — call ahead. One of the most photographed properties in St Kitts.", lat: 17.3861608, lng: -62.8286974, area: "Sandy Point", featured: false },
  { name: "Black Rocks Volcanic Runoff", category: "historical", duration: "30–45 minutes", description: "Hardened lava formations on the northeast Atlantic coast — the most accessible evidence of St Kitts' volcanic origin. The black rock shelves extend into the sea and the wave action against them is spectacular. A dramatic and undervisited spot.", tip: "Do not swim here — the Atlantic coast is rough and there are no lifeguards anywhere in St Kitts. This is a look-don't-touch stop.", lat: 17.4030125, lng: -62.7899505, area: "Dieppe Bay", featured: false },
  { name: "Rum Dawg Bar & Grill", category: "food_nightlife", duration: "1–2 hours", description: "A laid-back bar and grill on the northwest coast with cold drinks, grilled food, and serious ocean views. The kind of spot that rewards the drive up the western side of the island.", tip: "Check social media for current hours — hours can vary. Worth calling ahead.", lat: 17.3666336, lng: -62.8667253, area: "Northwest St Kitts", featured: false },
  { name: "Andy's Pizza & Pasta Takeout", category: "food_nightlife", duration: "20–40 minutes", description: "A no-frills takeout spot in Bird Rock doing solid pizza and pasta at local prices. Popular with residents who want a quick, filling meal without the tourist markup.", tip: "Takeout focused — call ahead to order. Bird Rock area.", lat: 17.2888205, lng: -62.7112377, area: "Bird Rock, Basseterre", featured: false },
  { name: "Bary's Bar & Grill", category: "food_nightlife", duration: "1–2 hours", description: "A local bar and grill in the Bird Rock area serving food and drinks in a casual setting. The kind of neighbourhood spot that feeds the community rather than tourists.", tip: "Local crowd, local prices. Bird Rock area.", lat: 17.2889299, lng: -62.7079296, area: "Bird Rock, Basseterre", featured: false },

  // THE BUSH
  { name: "Mount Liamuiga Trailhead", category: "nature", duration: "4–6 hours", description: "The dormant volcano that defines the island's skyline — 3,792 feet to the rim. Dense rainforest, giant ferns, vervet monkeys, and a crater at the top locals call the Giants Salad Bowl. On a clear day you can see six islands from the rim.", tip: "We always recommend hiring a local guide for hikes in St Kitts. Start before 7am. Bring more water than you think you need. Guides available from Saint Pauls village.", lat: 17.3831188, lng: -62.8518391, area: "Sandy Point", featured: true },
  { name: "Shitten Bay Trailhead", category: "nature", duration: "2–3 hours", description: "The trail access point for the rugged Atlantic-side coastline of the Southeast Peninsula. Wild terrain, dramatic cliffs, and coast views that most visitors never see. Challenging and worth every step.", tip: "We always recommend hiring a local guide for hikes in St Kitts. Atlantic-side — do not swim. Bring water and sun protection.", lat: 17.2253545, lng: -62.6532738, area: "Southeast Peninsula", featured: false },
  { name: "Saddle Hill Fortress", category: "nature", duration: "1.5–2.5 hours", description: "An 18th-century British fortification perched on a ridge with commanding views over Basseterre, the Caribbean, and Nevis. The hike up is short but steep — the ruins and the panorama at the top are the payoff.", tip: "We always recommend hiring a local guide for hikes in St Kitts. Early morning for the best light and cooler temps.", lat: 17.1220885, lng: -62.5808069, area: "Sandy Point", featured: false },
  { name: "Wingfield Rainforest Trail", category: "nature", duration: "1–3 hours", description: "Trail network through old-growth mahogany and wild orchids at Wingfield Estate — one of the oldest sugar estates in the Eastern Caribbean. Ancient Kalinago petroglyphs carved into boulders at the forest edge. Multiple difficulty levels.", tip: "We always recommend hiring a local guide for hikes in St Kitts. Best combined with a visit to Romney Manor next door. The petroglyphs are easy to walk past — get a guide.", lat: 17.3079, lng: -62.7793, area: "Old Road", featured: false },
  { name: "Lawyer Stephen's Cave Trailhead", category: "nature", duration: "2–3 hours", description: "Trail access to one of St Kitts' lesser-known cave systems, tucked into the rainforest on the island's interior. For the adventurous — this is not a tourist attraction, it's real terrain.", tip: "We always recommend hiring a local guide for hikes in St Kitts. Not suitable without a guide. Wear appropriate footwear.", lat: 17.3375, lng: -62.7873, area: "Central St Kitts", featured: false },
  { name: "Bat Cave Trailhead", category: "nature", duration: "1.5–2 hours", description: "Access point for the Bat Cave on the Southeast Peninsula — a dramatic coastal cave system on the Atlantic side. Home to a colony of bats and framed by rugged volcanic rock and sea views.", tip: "We always recommend hiring a local guide for hikes in St Kitts. Atlantic-side coastal terrain — stay aware of conditions.", lat: 17.306446, lng: -62.7886779, area: "Southeast Peninsula", featured: false },
  { name: "Radio Tower Hike", category: "nature", duration: "1.5–2.5 hours", description: "The trail up to the radio tower on the central ridge offers some of the best 360-degree views on the island — Caribbean on one side, Atlantic on the other, and the volcano looming to the northwest. A local favourite that most tourists miss entirely.", tip: "We always recommend hiring a local guide for hikes in St Kitts. The final approach is steep. Go early before the heat builds.", lat: 17.3041512, lng: -62.7753313, area: "Central St Kitts", featured: false },
  { name: "White House Bay Ridge Trail", category: "nature", duration: "1.5–2 hours", description: "A ridge trail above White House Bay on the Southeast Peninsula with sweeping views of the bay, the Atlantic coast, and Nevis. The bay below has a snorkeable shipwreck — combine them for a full morning.", tip: "We always recommend hiring a local guide for hikes in St Kitts. Sun protection essential — exposed ridgeline with no shade.", lat: 17.2262, lng: -62.6392, area: "Southeast Peninsula", featured: false },
  { name: "Brimstone Hill Fortress Trail", category: "nature", duration: "1–2 hours", description: "The trail network around the Brimstone Hill Fortress UNESCO World Heritage Site. More than just the fortress — the surrounding terrain has views across to Sint Eustatius, Saba, and Sint Maarten on clear days. Walking the ramparts and surrounding hillside is its own experience.", tip: "We always recommend hiring a local guide for hikes in St Kitts. Entrance fee applies to the fortress. Bring water — it's exposed and hot.", lat: 17.3477124, lng: -62.8388424, area: "Sandy Point", featured: false },

  // BEACHES
  { name: "Cockleshell Bay", category: "beach", description: "One of the most beautiful beaches on the Southeast Peninsula — a long crescent of white sand with calm, clear Caribbean water and a view straight across to Nevis. Popular but never overcrowded outside of cruise ship days. Lion Rock Beach Bar is right here.", tip: "⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", duration: "Half day to full day", lat: 17.2274984, lng: -62.6355075, area: "Southeast Peninsula", featured: true },
  { name: "Frigate Bay South (The Strip)", category: "beach", description: "The social heart of St Kitts beach life — a stretch of golden sand lined with beach bars, cold Caribs, and the kind of laid-back energy that makes you lose track of time. This is where the island comes to hang out. Mr. X's Shiggidy Shack is here. Wednesday and Saturday nights are legendary.", tip: "⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", duration: "Afternoon to evening", lat: 17.2792757, lng: -62.6942612, area: "Frigate Bay", featured: true },
  { name: "Banana Bay Beach", category: "beach", description: "A quiet, largely undeveloped beach at the southeastern tip of St Kitts with soft sand, turquoise water, and views across to Nevis. Far fewer visitors than Cockleshell next door, which is exactly the appeal.", tip: "⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", duration: "Half day", lat: 17.2268617, lng: -62.6419887, area: "Southeast Peninsula", featured: false },
  { name: "Majors Bay", category: "beach", description: "A tucked-away bay on the Southeast Peninsula that sees very little traffic. Calm, clear water and the kind of solitude that is getting harder to find on Caribbean beaches. Worth the extra few minutes of driving.", tip: "⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", duration: "1–3 hours", lat: 17.2198509, lng: -62.6555152, area: "Southeast Peninsula", featured: false },
  { name: "South Friars Bay", category: "beach", description: "A beautiful Caribbean-side beach that was home to Shipwreck and Discovery Beach Bars before the government eviction in 2026. The beach itself remains stunning — calm water, soft sand, and a more relaxed vibe than The Strip.", tip: "⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", duration: "Half day", lat: 17.2739212, lng: -62.6754302, area: "Southeast Peninsula", featured: false },
  { name: "North Friars Bay", category: "beach", description: "The Atlantic-side counterpart to South Friars Bay. Rougher water and stronger winds than the Caribbean side, but dramatic and beautiful. Not recommended for swimming — best for walking and photography.", tip: "⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts. Atlantic side — strong currents and unpredictable swells. Not recommended for swimming.", duration: "30–60 minutes", lat: 17.2778, lng: -62.6935, area: "Frigate Bay", featured: false },
  { name: "White House Bay", category: "beach", description: "A remote and largely undiscovered bay on the Southeast Peninsula with a sunken ship just offshore that makes for excellent snorkeling. The beach is rocky in places but the water is clear and the solitude is real.", tip: "⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", duration: "Half day", lat: 17.2495372, lng: -62.6635931, area: "Southeast Peninsula", featured: false },
  { name: "Dieppe Bay Black Sand Beach", category: "beach", description: "A striking black volcanic sand beach on the north Atlantic coast — dramatic, raw, and completely different from the Caribbean-side beaches. The dark sand and turbulent water give it an otherworldly feel. Worth the drive north for the scenery alone.", tip: "⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts. Atlantic side — strong currents. Not recommended for swimming.", duration: "30–60 minutes", lat: 17.4178149, lng: -62.8115168, area: "Dieppe Bay", featured: false },
  { name: "Frigate Bay North (Atlantic Side)", category: "beach", description: "The windswept Atlantic side of Frigate Bay — a long open beach with powerful waves and a very different energy from the calm Caribbean side just over the hill. Good for walking, kite flying, and watching the ocean. Not for swimming.", tip: "⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts. Atlantic side — strong rip currents. Do not swim here.", duration: "30–45 minutes", lat: 17.288754, lng: -62.6865379, area: "Frigate Bay", featured: false },
  { name: "Turtle Beach", category: "beach", description: "A quiet, natural beach at the southern tip of the Southeast Peninsula with calm, shallow water ideal for wading and snorkeling. The name comes from the sea turtles that nest and feed here. One of the more untouched stretches of sand on the peninsula.", tip: "⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", duration: "Half day", lat: 17.235505, lng: -62.629037, area: "Southeast Peninsula", featured: false },
  { name: "Sandy Bank Bay", category: "beach", description: "A secluded bay on the Southeast Peninsula accessible by a short walk or boat. Calm, clear water and very few visitors make it one of the more peaceful spots on the island. Good snorkeling off the rocks.", tip: "⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", duration: "Half day", lat: 17.249687, lng: -62.645598, area: "Southeast Peninsula", featured: false },
  { name: "Gong Beach", category: "beach", description: "A quieter beach on the Southeast Peninsula side, away from the main strip crowds. Clear water and a relaxed atmosphere — the kind of spot that rewards people who explore beyond the obvious.", tip: "⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", duration: "Half day", lat: 17.3286, lng: -62.8452, area: "Southeast Peninsula", featured: false },
  { name: "Pump Bay", category: "beach", description: "A scenic bay on the northwest coast near Sandy Point and Figtree — largely off the tourist map and all the better for it. The beach sits in a naturally sheltered position with good views across the Caribbean.", tip: "⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts.", duration: "1–3 hours", lat: 17.3653133, lng: -62.8580765, area: "Sandy Point", featured: false },
  { name: "Sea Glass Beach", category: "beach", description: "A hidden gem near Brumaire on the western coast where decades of ocean tumbling have produced an extraordinary collection of smooth, frosted sea glass in every colour. Not a swimming beach — this one is for the beachcombers and the curious. The sea glass density here is unlike anywhere else on the island.", tip: "⚠️ Swim at your own risk. There are no lifeguards anywhere in St Kitts. Come at low tide for the best sea glass hunting.", duration: "1–2 hours", lat: 17.2927139, lng: -62.7475826, area: "Brumaire", featured: false },
  // SCENIC DRIVES
  { name: "The Ring Road Circuit", category: "scenic_drive", description: "The definitive St Kitts drive — a roughly 35-mile loop around the entire island on a single road that takes you through every landscape, coast, and community the island has to offer. Caribbean sea on the west, Atlantic on the east, volcano in the middle. You will pass fishing villages, plantation ruins, black sand beaches, and stretches of rainforest canopy. No GPS needed — there is only one road and it goes all the way around.", tip: "Clockwise from Basseterre is the classic direction. Give yourself a full day if you want to stop properly. Fill the tank before you leave town.", duration: "Full day", lat: 17.3000, lng: -62.7500, area: "Island-wide", featured: true },
  { name: "Southeast Peninsula Road", category: "scenic_drive", description: "The most dramatic drive on the island — a ridge road that runs the length of the Southeast Peninsula with the Caribbean Sea on your right and the Atlantic Ocean on your left simultaneously. The road climbs, dips, and curves through dry scrub forest past salt ponds and hidden bays before ending at the beach bars of Cockleshell. Stop at Timothy Hill overlook for the most photographed view in St Kitts.", tip: "Pull over at Timothy Hill — the view of both coastlines at once is the shot. Drive it in the late afternoon when the light hits the water.", duration: "1.5–2.5 hours", lat: 17.2812, lng: -62.6789, area: "Southeast Peninsula", featured: true },
  { name: "The North Atlantic Run", category: "scenic_drive", description: "Head north from Basseterre through Cayon, Nicola Town, Saddlers, and Tabernacle to Dieppe Bay Town on the Atlantic coast. This is the St Kitts that most tourists never see — windswept black sand beaches, village rum shops, and a raw, unhurried pace of life that feels genuinely untouched. End the drive at Arthur's or Reef Bar in Dieppe Bay and eat fresh fish while the Atlantic crashes nearby.", tip: "Give yourself half a day minimum. The villages on this side of the island are worth slowing down for. Do not rush it.", duration: "Half day", lat: 17.4148, lng: -62.8140, area: "North Atlantic Coast", featured: false },
  { name: "Old Road to Sandy Point — The History Drive", category: "scenic_drive", description: "Drive the Caribbean coast west from Basseterre through Challengers, Half Way Tree, Old Road Town, Middle Island, and up to Sandy Point. This stretch of road passes more historically significant sites per mile than almost anywhere in the Caribbean — the site of the first British settlement, the grave of Sir Thomas Warner, Romney Manor, Wingfield Estate, and Brimstone Hill Fortress. Slow down and stop often.", tip: "Start at Old Road Town and work your way up to Brimstone Hill. Combine with Romney Manor and Caribelle Batik for a full day of history.", duration: "Half to full day", lat: 17.3469, lng: -62.8364, area: "Caribbean Coast", featured: false },
  { name: "Frigate Bay Ridge & Peninsula Lookouts", category: "scenic_drive", description: "A short but rewarding drive from the main island road down through Frigate Bay, up to the Timothy Hill ridge, and along the lookout points before dropping down to the Strip. The elevation changes are dramatic for such a short distance and the views from the ridge — across both the Caribbean and Atlantic simultaneously — are extraordinary. A great evening drive before ending up at the beach bars below.", tip: "Best driven just before sunset when both coastlines light up. Park at the Timothy Hill pulloff and walk to the edge.", duration: "45–90 minutes", lat: 17.2812, lng: -62.6789, area: "Frigate Bay", featured: false },
];

const SEED_SALT_POSTS = [
  {
    title: "The Beaches Nobody Tells You About",
    date: "2026-04-01",
    preview: "Cockleshell is beautiful. You already know that. Every tourist brochure, every Instagram account, every hotel concierge — all pointing you to the same patch of sand. Here's what they don't tell you...",
    body: `Cockleshell is beautiful. You already know that. Every tourist brochure, every Instagram account, every hotel concierge — all pointing you to the same patch of sand. Here's what they don't tell you.\n\nWhite House Bay has a shipwreck you can swim to in about ten strokes. Sandy Bank Bay on the Atlantic side will give you sea glass and total silence and absolutely zero other people on a Tuesday. Majors Bay looks unremarkable from the road and is extraordinary from the water.\n\nThe rule on this island is simple: if it's easy to get to, it's crowded. If the road is a little rough, it's worth it. If your rental car company would prefer you didn't go there — that's exactly where you should go.\n\nYou're on a volcanic island in the Caribbean with a rental car. Stop following the signs.`,
    emoji: "🏖️",
    tag: "Beaches",
    visible: true,
  },
  {
    title: "How to Do the Frigate Bay Strip Right",
    date: "2026-03-19",
    preview: "People come to the Strip and leave saying it was fine. Fine. On an island with this much rum and this many stars overhead, fine is an unacceptable outcome. Here's how to not waste it.",
    body: `People come to the Strip and leave saying it was fine. Fine. On an island with this much rum and this many stars overhead, fine is an unacceptable outcome.\n\nFirst: don't arrive before 9pm on a weekend. You'll be sitting alone in a plastic chair staring at the sea wondering if you got the wrong night. You didn't. The island just runs late.\n\nSecond: don't commit to one bar. Walk the whole strip before you plant your flag. Each bar has its own energy on any given night.\n\nThird: Wednesday is Trivia Night at Shiggidy Shack. If you are on this island on a Wednesday and you do not go to trivia night, I cannot help you.\n\nFourth: the rum punch is not a decoration. Respect it.`,
    emoji: "🍹",
    tag: "Nightlife",
    visible: true,
  },
  {
    title: "The Music Festival Is Not Optional",
    date: "2026-02-10",
    preview: "Every June, Warner Park Stadium becomes one of the best music venues in the world for three nights. I'm not exaggerating. The lineup this year includes Steel Pulse and Fantasia. June 25–27.",
    body: `Every June, Warner Park Stadium becomes one of the best music venues in the world for three nights. I'm not exaggerating.\n\nThe St Kitts Music Festival has been running for 28 years. In that time it has hosted names that have no business playing an outdoor stadium on a Caribbean island of 50,000 people — and that is exactly what makes it extraordinary.\n\nThis year: Steel Pulse, Fantasia, and a lineup that fills out from there. June 25 to 27. Warner Park.\n\nA few things to know: Night 3 is always the best night. The food outside the stadium gates is better than inside. Arrive later than you think you should. Leave later than you planned to.\n\nAnd if you're still in your hotel room at 10pm telling yourself you'll go next year — next year you'll say the same thing. Go this year.`,
    emoji: "🎵",
    tag: "Events",
    visible: true,
  },
  {
    title: "Stop Renting a Scooter. Get a Jeep.",
    date: "2026-01-22",
    preview: "I run a rental car company. I'm biased. But I'm also right. The Southeast Peninsula road, the drive up to Brimstone Hill, the back road to Dieppe Bay — none of these are scooter roads.",
    body: `I run a rental car company. I'm biased. But I'm also right.\n\nSt Kitts is a small island with a big road network and some of it is emphatically not designed for scooters. The Southeast Peninsula road is incredible — winding up over volcanic ridges with the Caribbean on one side and the Atlantic on the other — and it will eat a scooter and its rider without remorse if the wind gets involved.\n\nThe back road to Dieppe Bay, the agricultural tracks near Old Road, the drive up to Wingfield Estate — these demand four wheels and a little confidence.\n\nGet a Jeep. Roll the windows down. Do the Ring Road circuit counter-clockwise starting before 8am. Pull over every time you see a view worth stopping for.\n\nThe island is small enough that you can cover all of it in a day. Large enough that you'll want to do it twice.`,
    emoji: "🚙",
    tag: "Getting Around",
    visible: true,
  },
];

export async function registerRoutes(httpServer: Server, app: Express): Promise<Server> {
  // ── Seed / reseed on every boot ────────────────────────
  // Always wipe and reseed stops so code changes are reflected immediately
  storage.deleteAllStops();
  for (const stop of SEED_STOPS) {
    storage.createStop({ ...stop, visible: true } as any);
  }

  const existingPosts = storage.getAllSaltPosts();
  if (existingPosts.length === 0) {
    for (const post of SEED_SALT_POSTS) {
      storage.createSaltPost(post as any);
    }
  }

  // ── Public API ─────────────────────────────────────────
  app.get("/api/stops", (req, res) => {
    const { category } = req.query;
    if (category && typeof category === "string" && category !== "all") {
      return res.json(storage.getStopsByCategory(category));
    }
    return res.json(storage.getVisibleStops());
  });

  app.get("/api/stops/:id", (req, res) => {
    const id = parseInt(req.params.id);
    const stop = storage.getStop(id);
    if (!stop) return res.status(404).json({ message: "Stop not found" });
    return res.json(stop);
  });

  app.get("/api/salt-posts", (_req, res) => {
    return res.json(storage.getVisibleSaltPosts());
  });

  // ── Admin auth ─────────────────────────────────────────
  app.post("/api/admin/login", (req, res) => {
    const { password } = req.body;
    if (password === ADMIN_PASSWORD) {
      return res.json({ ok: true });
    }
    return res.status(401).json({ message: "Wrong password" });
  });

  // ── Admin: Stops CRUD ──────────────────────────────────
  app.get("/api/admin/stops", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    return res.json(storage.getAllStops());
  });

  app.post("/api/admin/stops", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    const stop = storage.createStop(req.body);
    return res.json(stop);
  });

  app.put("/api/admin/stops/:id", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    const id = parseInt(req.params.id);
    const stop = storage.updateStop(id, req.body);
    if (!stop) return res.status(404).json({ message: "Stop not found" });
    return res.json(stop);
  });

  app.delete("/api/admin/stops/:id", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    storage.deleteStop(parseInt(req.params.id));
    return res.json({ ok: true });
  });

  // ── Admin: Salt Posts CRUD ─────────────────────────────
  app.get("/api/admin/salt-posts", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    return res.json(storage.getAllSaltPosts());
  });

  app.post("/api/admin/salt-posts", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    const post = storage.createSaltPost(req.body);
    return res.json(post);
  });

  app.put("/api/admin/salt-posts/:id", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    const id = parseInt(req.params.id);
    const post = storage.updateSaltPost(id, req.body);
    if (!post) return res.status(404).json({ message: "Post not found" });
    return res.json(post);
  });

  app.delete("/api/admin/salt-posts/:id", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    storage.deleteSaltPost(parseInt(req.params.id));
    return res.json({ ok: true });
  });

  // ── Public: validate unlock code ───────────────────────
  app.post("/api/unlock", (req, res) => {
    const { code } = req.body;
    if (!code) return res.status(400).json({ valid: false });
    const cleaned = (code as string).trim().toUpperCase();
    const paid    = sqlite.prepare(`SELECT value FROM app_settings WHERE key = 'unlock_code_paid'`).get() as { value: string } | undefined;
    const friends = sqlite.prepare(`SELECT value FROM app_settings WHERE key = 'unlock_code_friends'`).get() as { value: string } | undefined;
    const stripeRow = sqlite.prepare(`SELECT value FROM app_settings WHERE key = 'stripe_link'`).get() as { value: string } | undefined;
    const valid = cleaned === paid?.value?.toUpperCase() || cleaned === friends?.value?.toUpperCase();
    return res.json({ valid, stripeLink: stripeRow?.value ?? '' });
  });

  // ── Public: get Stripe link ────────────────────────────
  app.get("/api/stripe-link", (_req, res) => {
    const row = sqlite.prepare(`SELECT value FROM app_settings WHERE key = 'stripe_link'`).get() as { value: string } | undefined;
    return res.json({ stripeLink: row?.value ?? '' });
  });

  // ── Admin: manage unlock codes ─────────────────────────
  app.get("/api/admin/settings", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    const rows = sqlite.prepare(`SELECT key, value FROM app_settings`).all() as { key: string; value: string }[];
    const settings: Record<string, string> = {};
    rows.forEach(r => settings[r.key] = r.value);
    return res.json(settings);
  });

  app.put("/api/admin/settings", (req, res) => {
    if (!checkAdmin(req)) return res.status(401).json({ message: "Unauthorized" });
    const { key, value } = req.body;
    sqlite.prepare(`INSERT OR REPLACE INTO app_settings (key, value) VALUES (?, ?)`).run(key, value);
    return res.json({ ok: true });
  });

  return httpServer;
}

function checkAdmin(req: any): boolean {
  const auth = req.headers["x-admin-password"];
  return auth === ADMIN_PASSWORD;
}
